DEFAULT_NAME_HASHING_METHOD = 'sha1'
DEFAULT_TARGET_DIRECTORY = 'resized-images'
DEFAULT_REDIS_KEY = 'flask-resize'

JPEG = 'JPEG'
PNG = 'PNG'
SVG = 'SVG'
SUPPORTED_OUTPUT_FILE_FORMATS = (JPEG, PNG)
PROGRESSIVE_FORMATS = (PNG, SVG)
